### PR TITLE
[ issue_114 ] - Moving fact_store as we require uses to use python_path in deployment.

### LINKED ISSUE #114: [Bug] Remove requirement for PYTHONPATH for deploying Fact_Store.
**Describe the bug**
During deployment it is required that we set PYTHONPATH as it won't find the fact_store. We should move this to a subfolder.

**To Reproduce**
```bash

oc new-app python~https://github.com/zmhassan/log-anomaly-detector.git#issue_83 -e PYTHONPATH='/opt/app-root/src'  -e APP_FILE='fact_store/app.py' --name='factstore-zmhassan' 
```

**Expected behavior**

### PR DESCRIPTION
**Pull request by zmhassan**
# PR Details

Deployment of factstore requires PYTHONPATH env var to be set. We should not require uses to do that. 

## Description

We want to make fact_store a subproject. Which will allow for easier reuse of code and allow for packaging the full system.

## Related Issue

Fixes #114 
## Motivation and Context

We found it difficult to import libraries like Elasticsearch when we want to fetch messages or do more automation.

## How Has This Been Tested

```bash
pipenv update
```

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## More Details
None

### CODE REVIEW

**Comment by zmhassan** [comment]
@durandom I'm just moving the fact_store repo to be under log_anomaly_detector so we can:

- Reuse code across log-anomaly-detector storage classes
- Be able to do some validation and fetch messages from Elasticsearch.
- Allow for deployment without requiring us to set PYTHONPATH with s2i.

**Comment by durandom** [comment]
kicking travis

**Comment by durandom** [comment]
@zmhassan travis is 🔴

**Comment by zmhassan** [comment]
> @zmhassan travis is 🔴

Ohh weird when I run it on my machine it works.

**Comment by zmhassan** [comment]
I'm going to fix this now

**Comment by goern** [comment]
looks like Zuul is executing the pytests faster than travis... https://managesf.thoth-station.ninja/logs/15/115/109706a6f6f6b379ea471e13ffc000d3f9952fc6/check/thoth-pytest/92e01bb/ara-report/result/890df37d-6f06-48f8-950d-61dc9a756b06/

**Comment by durandom** [comment]
@goern what is:

> local/check — check status: failure

?

**Comment by durandom** [comment]
@goern is this: https://github.com/AICoE/log-anomaly-detector/blob/master/.zuul.yaml#L3 ?
So you named it `check` ?
This needs to be more descriptive...

**Comment by durandom** [comment]
kicking zuul...

zuul reports errors - but travis is fine

**Comment by goern** [comment]
close-open-spam?! Try 'recheck' as a single word comment

**Comment by zmhassan** [comment]
I'm suspecting zuul is building the setup.py for some reason and I've removed s3fs dependency. So maybe its complaining. Going to send up another PR.

**Comment by goern** [comment]
'check' and 'gate' are the zuul default names for the pre-merge pipeline and the merge pipeline, local is the zuul tenant name, also a default

**Comment by zmhassan** [comment]
@goern so my acceptance criteria is if travis pass then we are good to merge this. I am not sure if zuul has been configured correctly. What do you think @durandom

**Comment by goern** [comment]
Nice try :p but see that?! If you fix the errors zuul turns green. I'm pretty sure it is configured correctly, the pytest setup we have created for Thoth might be a little bit different from Travis

**Comment by zmhassan** [comment]
Whats the `thoth-coala : FAILURE in 36s` error then? How do I fix that?

**Comment by durandom** [comment]
@zmhassan @goern this needs some click wizadry:

click -> ara report -> coala -> tasks -> action: command

then you'll see that:

https://managesf.thoth-station.ninja/logs/15/115/e4b1e9ef061ffbd1711ce8ead57888ba32ff3fe2/check/thoth-coala/756ee81/ara-report/result/1571ce8e-2350-44f1-b086-6c085082da99/

but let's wait until we're educated to run coala locally

it also seems that coala checks all files? not only the changes?

I'll merge this.

**Pull request merged**
