### PR TITLE
used black to reformat all the things

### PR DESCRIPTION
**Pull request by goern**
docstrings and GPL headers are missing all over the place!!

Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by durandom** [comment]
@goern can you give the cmd that you used to reformat this?

@zmhassan pls review

**Comment by goern** [comment]
```
pipenv install --pre --dev black
black .
```

**Comment by zmhassan** [comment]
@goern I'm reviewing now

**Comment by goern** [comment]
We can, but do you really see an advantage in having lines 80 char long? Nowadays we all have wide screens and 120 seems way more appropriate

**Comment by durandom** [comment]
Yea, let's stick to the thoth established style and create a CoE common style.
I'm 👍 for merging

**Comment by zmhassan** [comment]
I'd like more information on the following:
```
Build failed.
thoth-coala : FAILURE in 49s
```

We can disable the pylint and make it take more than 80 char limit.

`pylint --max-line-length=120`

Also is there a way we can make stickler-ci not flag this as an error. Or can we remove it completely?

**Comment by durandom** [comment]
> I'd like more information on the following:
> 
> ```
> Build failed.
> thoth-coala : FAILURE in 49s
> ```

You can click on the link and look at that ara report. The FAILUREs are burried in there somewhere. Just click around.

> We can disable the pylint and make it take more than 80 char limit.
> 
> `pylint --max-line-length=120`
> 
> Also is there a way we can make stickler-ci not flag this as an error. Or can we remove it completely?

Yes, I'll remove stickler, just ignore him for now.

**Comment by zmhassan** [comment]
LGTM. We can merge this.

**Pull request merged**
