### PR TITLE
Adding better docs in readme.md

### PR DESCRIPTION
**Pull request by zmhassan**
## Problem
Documentation doesn't give details on what the environment variables mean.

## Solution
We have provided better documentation for the project.

### CODE REVIEW

**Comment by zmhassan** [comment]
@durandom Can we get reviewed on this and/or merge this as this ?

**Comment by goern** [comment]
not all checks pass, so it's not ready for review.

**Comment by zmhassan** [comment]
I'm going to cl

**Comment by zmhassan** [comment]
> not all checks pass, so it's not ready for review.

Hi @goern , I was wondering if I can get more detail about what checks are being used as I think this was a readme file update?

**Comment by goern** [comment]
what is cl?

**Comment by zmhassan** [comment]
> Build failed.
> 
> * [thoth-coala ](https://managesf.thoth-station.ninja/logs/21/121/45b0bc046c982d0f4118027d1cf8fea0297395cb/check/thoth-coala/dd51c2e/) : FAILURE in 44s
> * [thoth-pytest ](https://managesf.thoth-station.ninja/logs/21/121/45b0bc046c982d0f4118027d1cf8fea0297395cb/check/thoth-pytest/106ec66/) : FAILURE in 2m 09s

@goern Since you added this stuff I have some questions about what is being checked here?

**Comment by zmhassan** [comment]
Our travis ci passes green for pytests and this additional stuff added says that pytests fail. If I run it locally it passes. Am I missing something?

**Comment by zmhassan** [comment]
Hey  @goern, in the last PR I saw that coala was failing and I assume this is not something that I new that happened because of readme documentation updates. So I'll investigate this some more. https://github.com/AICoE/log-anomaly-detector/pull/116

**Comment by goern** [comment]
After looking thru https://managesf.thoth-station.ninja/logs/21/121/45b0bc046c982d0f4118027d1cf8fea0297395cb/check/thoth-pytest/106ec66/ara-report/result/60bc482f-ca90-4b55-897f-bb6a502839ea/ it looks like you are building a native module. This is not supported by thoth-zuul-infra.

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
Thoth's Zuul job 'thoth-pytest' now has the capability to build native extensions. Have fun!

@AICoE/thoth-station

**Comment by zmhassan** [comment]
@goern So now when your checks run pytests it should all work as expected. As for `coala` I don't know why that is failing? Looking through the logs for the failure looks like I found this error message:

```
Task: Gathering Facts
Tags: always
Host: pod
Time: 2019-05-02 18:43:49

Ansible version: 2.5.15

Module_stderr
/bin/sh: /usr/bin/python2: No such file or directory
command terminated with exit code 127
Msg
MODULE FAILURE
Rc
127 
```

**Comment by durandom** [comment]
@zmhassan did you run coala locally? As shown in @fridex bluejeans presentation?

**Comment by zmhassan** [comment]
@durandom I ran coala. I don't think that is the problem here. I never seen `thoth-coala : FAILURE in 42s` pass. This was broken before I even made this PR. Check Christoph's PR: #116  It says this was failing and I don't know if its a bug in their system or what?

**Comment by fridex** [comment]
I see coala errors being reported, to show them:

1. click on the "thoth-coala" (accept the certificate if necessary)
2. click on "ara-report"
3. expand "2 tasks" by clicking on the failure coala.yaml scenario
4. click on "FAILED" in a row with "thoth-coala : Run Coala" (a dialog window will pop-up with errors reported)

**Comment by zmhassan** [comment]
@fridex Is there a way I can reproduce this locally. I think this system is broken.

**Comment by fridex** [comment]
You need to install [coala-bears](https://pypi.org/project/coala-bears/).

**Comment by zmhassan** [comment]
Yup installed coala. Very nice tool. It's giving me suggestions on adding comments and linting. And it can apply the fix for me.

**Comment by zmhassan** [comment]
@durandom So this PR is ready for review and please merge if this looks good.

**Pull request merged**
