### PR TITLE
 Documentation for project website

### PR DESCRIPTION
**Pull request by zmhassan**
## Description

Provide documentation for the project and give details on how this project.

### CODE REVIEW

**Comment by zmhassan** [comment]
@durandom @MichaelClifford This is first phase of documentation for LAD.

**Comment by durandom** [comment]
❤️ documentation. That's great. Can you get coala to pass?

**Comment by zmhassan** [comment]
@durandom The docs are posted here:

https://log-anomaly-detector.readthedocs.io/en/latest/

**Comment by zmhassan** [comment]
@durandom Please review.

**Pull request merged**
