### PR TITLE
Cleaning up bad files

### PR DESCRIPTION
**Pull request by zmhassan**
Removing pipfile.lock as its not supposed to be here.

### CODE REVIEW

**Comment by vpavlin** [comment]
@fridex Can you please explain why we need `Pipfile.lock`?:-)

**Comment by fridex** [comment]
> Removing pipfile.lock as its not supposed to be here.
>> @fridex Can you please explain why we want Pipfile.lock?:-)

I will cite [stackoverflow](https://stackoverflow.com/questions/46330327/please-explain-the-usage-of-pipfile-and-pipfile-lock):

> The pipenv.lock file is intended to specify, based on the packages present in Pipfile file, which specific version of those should be used, avoiding the risks of automatically upgrading packages that depend upon each other and breaking your project dependency tree.

Basically to have reproducible environment.

**Comment by zmhassan** [comment]
@fridex @vpavlin I got a notification from github saying this could be a security vulnerability. So I've removed it.

**Comment by fridex** [comment]
> @fridex @vpavlin I got a notification from github saying this could be a security vulnerability. So I've removed it.

Are you sure about this? :)

**Comment by vpavlin** [comment]
You just merged a PR that broke Travis builds, did you test your change before merging or did you blindly brake the master?

**Pull request merged**
