### PR TITLE
Validating factstore for duplicate values

### PR DESCRIPTION
**Pull request by zmhassan**
### Bug
Referencing issue: #72 
When users post feedback they may report the duplicate feedback. 

### Solution
We only need to know about it 1 time and once we know our system should log it in our parquet store. We want to use an efficient data structure for this sort of thing as data may grow. We are using bloom filter. If we insert a record into the parquet store we also let the bloom filter know.

Properties of bloom filter: 
* False Positive:  if bloom filter tells you item is in the set then it is probably true. We set the accuracy to 99.999% with this library.
* False Negative:if bloom filter tells you item is not in the set then it is always true.

We want to make sure this fix is scalable

### CODE REVIEW

**Comment by zmhassan** [comment]
I've also included some unit tests to validate this.

**Comment by zmhassan** [comment]
This PR is ready for review @durandom

**Comment by durandom** [comment]
@zmhassan I can't review this. 275 changed files?
I'm good with renaming. But then do it in one commit and make the changes in another commit...

**Comment by zmhassan** [comment]
I could probably remove a lot of files here.

**Comment by durandom** [comment]
then please do the remove in one commit, which is called, remove files. Just put yourself into the shoes of a reviewer....

**Comment by zmhassan** [comment]
I'm going to clean this up.

**Comment by zmhassan** [comment]
@durandom Code changes are in the 1st commit and the files removed are in the 2nd commit. Thank you for your patience.

**Comment by zmhassan** [comment]
@durandom This is ready for final review.

**Comment by zmhassan** [comment]
I've removed any javascript or css file we are not using and instead I am fetching the js/css via cdn.

**Pull request merged**
