### PR TITLE
[WIP] Adding fix to storage

### PR DESCRIPTION
**Pull request by zmhassan**
# Description

Removing the check for  "value" from the elasticsearch datasource.

### CODE REVIEW

**Comment by zmhassan** [comment]
@4n4nd Please review this change. And let me know if its okay for me to update this as it was working prior now we can't access elasticsearch logs in prod.

**Comment by zmhassan** [comment]
Fixes #287

**Comment by HumairAK** [comment]
For reference this is the error that now shows up using the elastic search deployment using our templates: 
```
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'message'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "app.py", line 56, in <module>
    cli(auto_envvar_prefix="LAD")
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 52, in run
    anomaly_detector.run(single_run=single_run)
  File "/opt/app-root/src/anomaly_detector/anomaly_detector_facade.py", line 56, in run
    self.start_job()
  File "/opt/app-root/src/anomaly_detector/anomaly_detector_facade.py", line 76, in start_job
    self.pipeline.execute_steps()
  File "/opt/app-root/src/anomaly_detector/jobs/core.py", line 162, in execute_steps
    step.execute()
  File "/opt/app-root/src/anomaly_detector/jobs/core.py", line 85, in execute
    recreate_model=self.recreate_model)
  File "/opt/app-root/src/anomaly_detector/decorator/utils.py", line 16, in wrapper
    rtn = func(*args, **kwargs)
  File "/opt/app-root/src/anomaly_detector/adapters/som_model_adapter.py", line 73, in preprocess
    dataframe, raw_data = self.storage_adapter.load_data(config_type)
  File "/opt/app-root/src/anomaly_detector/decorator/utils.py", line 16, in wrapper
    rtn = func(*args, **kwargs)
  File "/opt/app-root/src/anomaly_detector/adapters/som_storage_adapter.py", line 43, in load_data
    false_positive=false_data)
  File "/opt/app-root/src/anomaly_detector/adapters/som_storage_adapter.py", line 22, in retrieve_data
    false_positive))
  File "/opt/app-root/src/anomaly_detector/storage/storage_proxy.py", line 18, in retrieve
    return self.source.retrieve(storage_attribute)
  File "/opt/app-root/src/anomaly_detector/storage/es_storage.py", line 128, in retrieve
    es_data_normalized = pandas.DataFrame(json_normalize(es_data)["message"])
  File "/opt/app-root/lib/python3.6/site-packages/pandas/core/frame.py", line 2980, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/app-root/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'message'
```

**Comment by zmhassan** [comment]
@HumairAK Can you paste the log message your seeing?

**Comment by HumairAK** [comment]
From the pod (debug mode) I can reach elastic search, here's a curl output of the logs: 
```
(app-root) sh-4.2$ curl -X GET lad-elasticsearch-service.lad.svc:9200/_search?pretty
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "lad-2019.10.08",
        "_type" : "log",
        "_id" : "qWLRrG0BhxR4e5Xp_Rfc",
        "_score" : 1.0,
        "_source" : {
          "message" : "Order placed for 1 items of bananas which costs 5",
          "@timestamp" : "2019-10-08T19:21:44Z",
          "tags" : [
            "ecommerce"
          ]
        }
      },
      {
        "_index" : "lad-2019.10.08",
        "_type" : "log",
        "_id" : "qmLSrG0BhxR4e5XpARfL",
        "_score" : 1.0,
        "_source" : {
          "message" : "Order placed for 1 items of onions which costs 3",
          "@timestamp" : "2019-10-08T19:21:47Z",
          "tags" : [
            "ecommerce"
          ]
        }
      }
    ]
  }
}

```

**Comment by zmhassan** [comment]
@HumairAK Wonder if the problem is getting caused because there is no data in the timespan of when you retrain.

**Comment by zmhassan** [comment]
So I ran a query on elastic and it returns data. However the client here doesn't get the data. Something weird is going on here?

**Comment by 4n4nd** [comment]
@zmhassan I specifically made that change in #261 because the index is not right.
`es_data["hits"]["total"]` just returns a dict which is never equal to `0`.

**Comment by zmhassan** [comment]
This is a not an issue in prod. I believe it was an issue in the elasticsearch setup for minishift. @HumairAK confirmed this is working so we will close this.

**Comment by zmhassan** [comment]
We need to remove this part as the code was working prior to this '["value"]' being added @4n4nd Can we remove this ?

**Comment by 4n4nd** [comment]
It seems like the response structure is different for older versions of Elasticsearch

**Comment by 4n4nd** [comment]
For es version 5: https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-request-body.html
For es version 7: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-track-total-hits.html

**Comment by zmhassan** [comment]
I think we should probably expose a version of what elastic search they use. And process accordingly

**Comment by 4n4nd** [comment]
ES v5 and v6 use this structure, so I think it makes sense to approve this change

**Pull request merged**
