### PR TITLE
Experimental Feature: Adding graph visualization of ML Training RUN

### PR DESCRIPTION
**Pull request by zmhassan**
# Description
Wanted to see a visual view of the process that an ML run is executing. Added some javascript to visualize that. 
 
demo-graph

### CODE REVIEW

**Comment by zmhassan** [comment]
I did this on weekend so hope its fine for me to contribute on my own time. 👍

**Comment by MichaelClifford** [comment]
This is a cool interactive visualization, but it is unclear to me what value this tool brings to the project. Would the graph ever be different? Could this be used to diagnose possible problems in the future? Or is it an interactive graph of the fixed training run ?

**Comment by zmhassan** [comment]
I was thinking to have this graph in a visual way what step it is in the process of training and prediction.

**Comment by zmhassan** [comment]
This PR is highly experimental but serves no added value so I'm closing this PR.

**Pull request closed without merging**
