### PR TITLE
Adding simple decorator utility to log latency of function

### PR DESCRIPTION
**Pull request by zmhassan**
## Description

We have logging statements that measure different parts of the system. Why not have a centralized `@latency_logger(name)` to measure how long a function took.

### CODE REVIEW

**Comment by zmhassan** [comment]
Output will look something like this:
```bash
SomModelAdapter  function compute_score() took 5.2012059688568115 s
SomModelAdapter  function train() took 5.2623066902160645 s
```

**Comment by durandom** [comment]
@zmhassan needs rebase

**Comment by zmhassan** [comment]
@durandom Its rebased and ready for you to review. 👍

**Comment by durandom** [comment]
@zmhassan please rebase

**Pull request merged**
