### PR TITLE
Renaming in anomaly_detector.py

### PR DESCRIPTION
**Pull request by MichaelClifford**
While looking through `anomaly_detector.py`, realised that some of the variable and function names did not adequately represent what they were, making it difficult for a new users to understand the code. 

Renamed a few variables to, hopefully, make the code more readable.

### CODE REVIEW

**Comment by zmhassan** [comment]
recheck

**Comment by zmhassan** [comment]
@goern The bot seems to be down?? Any idea??@fridex

**Comment by fridex** [comment]
> @goern The bot seems to be down?? Any idea??@fridex

Seems to be ok now!?

**Comment by zmhassan** [comment]
@MichaelClifford This looks good to me. @MichaelClifford Please squash/rebase. And I'll merge this.

**Comment by MichaelClifford** [comment]
Mest up the commits in this PR. Closing. Will resubmit when fixed.

**Pull request closed without merging**
