### PR TITLE
Removing dependency on elasticsearch env vars. Defaulting to using configmap with yaml to deploy

### LINKED ISSUE #119: Config for Storage Providers requires bug unable to load configs from configmap
**Describe the bug**
When deploying log anomaly detector we often have to set env vars. We have added a feature where we can pass in a configuration file via configmap. The problem is when using elasticsearch the configurations don't get initialized.

**To Reproduce**

**Expected behavior**
I should be able to load all configurations via configmap instead of env vars.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by zmhassan**
## Description

Currently we want to deploy LAD with elasticsearch as the data input provider. We would like to make it configurable via yaml file with configmap. Currently there is bug and this PR should remove the dependency to inject env vars.

## Related Issue

Fixes #119  

## Motivation and Context

We would like to be able to run LAD with different configmaps to run our application. Currently there is a dependency on env vars.

## How Has This Been Tested
Update .env_config.yaml with elasticpoint and it should connect. Previously this would fail with host not found error.
```bash
python app.py run --config-yaml .env_config.yaml
```

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vpavlin** [comment]
TBH, I don't like this, the original design was to have storage backends extensible and (ideall) swappable. This PR makes it hard as you are moving configuration away from backend implementation.

To me it would make more sense to figure out how to fix the "bug" you are referring to - i.e. having the storage config subclass load not only from env, but also from the yaml file.

This PR seems to be more a workaround and moving away from modular design rather than a proper solution. 

Also, I just noticed: https://github.com/AICoE/log-anomaly-detector/blob/894acf07b50b1f811112afb436f04ea7405ac63d/anomaly_detector/config.py#L122-L129 - there is a same code copied twice in that file, which is error prone and a bad practice, please keep in mind to refactor that.

**Comment by zmhassan** [comment]
Good feedback. I'll fix that.

**Comment by zmhassan** [comment]
@vpavlin I've fixed the issue. Configurations will work for both config.yaml and env var. @durandom This PR has been out here for a while. Hope we can merge this.

**Comment by zmhassan** [comment]
@vpavlin Also I'm thinking of redesigning the structure of how configurations get loaded in a future PR. For now my main goal is having log anomaly detection service running with no failure or bug.

**Pull request merged**
