### PR TITLE
Ensure single instance of Task Queue exists in the lifetime of application.

### PR DESCRIPTION
**Pull request by zmhassan**
## Description:
An api should enforce rules for how users will interact with it. As Task queue is very core to Log anomaly detector. We should have it be a singleton class. Which only has 1 instance.

### CODE REVIEW

**Comment by zmhassan** [comment]
@durandom First Commit is a cherry pick of another PR. 2nd commit has the relevent changes for this PR.

**Comment by zmhassan** [comment]
@durandom This PR is ready for review

**Comment by durandom** [comment]
@zmhassan confliction files...  can you find out why there is a conflict?

**Comment by zmhassan** [comment]
Im fixing it.

**Comment by durandom** [comment]
> Im fixing it.

Can you please find out why there was a conflict, to avoid this in the future?

**Pull request merged**
