### PR TITLE
refactor playbook to roles

### PR DESCRIPTION
**Pull request by HumairAK**
This PR converts the playbooks into roles and includes them in a master playbook in an effort to allow users to deploy the entire stack in a single command, with minimal effort. Instructions are also included on how to leverage this playbook. The PR also includes some minor fixes to the docs.

### CODE REVIEW

**Comment by zmhassan** [comment]
@HumairAK Please apply fixes and I will approve this PR.

**Comment by 4n4nd** [comment]
@HumairAK I think this needs rebasing

**Comment by HumairAK** [comment]
@4n4nd and @zmhassan - issues have been resolved

**Comment by 4n4nd** [comment]
LGTM :+1:

**Comment by zmhassan** [comment]
LGTM

**Pull request merged**
