### PR TITLE
Adding update to pypi

### PR DESCRIPTION
**Pull request by zmhassan**
# Description
Updated dependencies cli.

### CODE REVIEW

**Comment by zmhassan** [comment]
Fixes : #292

**Comment by goern** [comment]
Have a look at thamos, we have quiet a few tricks for setup.py

**Comment by zmhassan** [comment]
@HumairAK Please review this PR. As CLI is broken now

**Comment by zmhassan** [comment]
Oh I have a fix for this.

**Comment by zmhassan** [comment]
@HumairAK Now its ready for review.

**Comment by 4n4nd** [comment]
@zmhassan what are we using `boto3` for?

**Comment by zmhassan** [comment]
@4n4nd We will be using it to get logs it will be part of the source/sinks.

**Pull request merged**
