### PR TITLE
Adding TDD to false positives with test case to validate if model can…

### LINKED ISSUE #105: Continuous learning from false positives
**Describe the problem**
When users get a false predictions then they should be able to give us feedback. We have a fact-store for this purpose. The next step is to train the model on new log lines and fetch the false predictions that where reported. @MichaelClifford lets discuss what updates need to be done for providing this functionality.

**More Details**
I wanted to start this as a discussion first and then look at what needs to be changed.

### PR DESCRIPTION
**Pull request by zmhassan**
This PR is work in progress and shall be used to start a discussion on how we can implement this test case to validate our assumptions.

## Description

This PR contains a unit test to validate if the model can learn from false positives. We are simulating the scenario of a human in the loop providing feedback that a log which is not an anomaly has be flagged incorrectly. Our model should learn from this and not report the same false prediction. We can filter programmatically but this is not machine learning. We should have the model learn from the data over time and get smarter.

## What is included in this PR
Unit test to validate this. 
What is missing is a function for passing in feedback into Self-organizing map model?

@MichaelClifford What do you recommend is the best approach in passing false positives into SOM?

## Related issue
Fixes #105

### CODE REVIEW

**Comment by zmhassan** [comment]
The test case should be **red** and fail unless we are able to pass in the false positives into SOM and if its true that SOM can learn from false positive data.

**Comment by zmhassan** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Comment by zmhassan** [comment]
@goern says "seems to be a problem between zuul and Openshift"

**Comment by zmhassan** [comment]
[[OKR9] Retraining of LAD based on user feedback](https://trello.com/c/EESYvI4p/247-okr9-retraining-of-lad-based-on-user-feedback)

**Comment by zmhassan** [comment]
[[OKR9] Retraining of LAD based on user feedback](https://trello.com/c/EESYvI4p/247-okr9-retraining-of-lad-based-on-user-feedback)

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
@zmhassan do you know how much memory your pytests require?

**Comment by goern** [comment]
recheck

**Comment by zmhassan** [comment]
> @zmhassan do you know how much memory your pytests require?

One sec I'm gonna try to benchmark it.

**Comment by zmhassan** [comment]
@goern we use about 400MB
LAD_Memory

**Comment by zmhassan** [comment]
So I tried to use the `python3 setup.py test` command and it runs all our tests should be okay to bump to the memory to 450-500mb

Figure_1

**Comment by goern** [comment]
We have started working with Zuul engineering to identify the problem.

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
Related Ticket: https://url.corp.redhat.com/b7d1e80

**Comment by zmhassan** [comment]
@durandom So I removed the WIP and rebased. Awaiting on the merge ??

**Pull request merged**
