### PR TITLE
Removing unused Som Model file

### PR DESCRIPTION
**Pull request by zmhassan**
### Background

We had performance bottleneck where our training was taking 45 mins and we replaced this class with a library that does SOM with concurrency. We no longer need this code. It's removed.

### CODE REVIEW

**Comment by zmhassan** [comment]
The issue being worked on has details here:

#63

**Comment by durandom** [comment]
@MichaelClifford this is your code. Please merge if you feel that's good

**Comment by vpavlin** [comment]
LGTM

**Comment by MichaelClifford** [comment]
We switched the SOM code that I wrote for the SOMPY package to address some of the speed issues that were causing a bottle-neck for further development a while back, but it has not been extensively tested with regard to prediction performance. So, unless its causing a major issue by existing in the code base I'd prefer to keep it available for the time being.

**Comment by durandom** [comment]
@zmhassan I'd also just keep it, and if it's just for the sake of testing different models...

**Comment by zmhassan** [comment]
Good idea.

**Comment by vpavlin** [comment]
As the agreement is to keep it, let's close the PR

**Pull request closed without merging**
