### PR TITLE
Removing requirements.txt

### PR DESCRIPTION
**Pull request by zmhassan**
### Background
Per issue #42 . Pipfile is the standard way for us to install dependencies. I've removed requirements.txt

### CODE REVIEW

**Comment by vpavlin** [comment]
a) Issue #42 talks about removing file with a typo in name, unrelated to removing requirements.txt file
b) How does fact_store install it dependencies now when you removed the requirements.txt? I don't see Flask being mentioned anywhere

**Comment by zmhassan** [comment]
All dependencies for fact-store are in the main Pipfile in the root of the project.

**Comment by vpavlin** [comment]
I don't see any of these

```
Flask==0.12.4	
fastparquet	
s3fs	
git+https://github.com/jaybaird/python-bloomfilter
```

in

https://github.com/AICoE/log-anomaly-detector/blob/master/Pipfile

What am I missing?

**Comment by zmhassan** [comment]
@vpavlin Fact_store is being added in via this PR: https://github.com/AICoE/log-anomaly-detector/pull/75/files

**Pull request merged**
