### PR TITLE
update factstore to use sqlalchemy

### PR DESCRIPTION
**Pull request by HumairAK**
This PR: 
- Converts Factstore to use Flask Alchemy instead of SQL Alchemy raw
- Restructured Factstore code to accommodate Flask Alchemy
- Adds cli support to launch factstore using gunicorn for production mode, usage instructions: 
```
# To use gunicorn use the --env and --worker flags 
$ app.py ui --env prod --workers 3 --port 5000
# use --help flag for more details 
```
- Updated tests to support flask alchemy code and added newer tests for the api. 
- Fixed bug found [here](https://github.com/AICoE/log-anomaly-detector/blob/master/anomaly_detector/fact_store/app.py#L73) (bool('some str') will always return true)

In general the usage via command line stays the same, so templates/playbooks need not be updated right away, but should eventually be moved to adopt Gunicorn.

### CODE REVIEW

**Comment by 4n4nd** [comment]
@HumairAK did you deploy and test this on oc?

**Comment by zmhassan** [comment]
@goern Wasn't the bot supposed to automatically merge when approved?

**Comment by zmhassan** [comment]
LGTM

**Comment by zmhassan** [comment]
regate

**Pull request merged**
